version: '3'

services:
  ########################################################################
  # NEXT.JS APPLICATION
  ########################################################################
  app:
    # DO NOT USE build: in Swarm for rolling updates. Use an image from a registry:
    image: "ghcr.io/zaidalshreef/neonova:latest"
    # container_name: "nextjs-app"
    restart: always
    # In Docker Swarm mode, 'ports:' is typically placed in the Traefik service
    # or use "mode: host" or "mode: ingress" if you want direct exposure. 
    # We'll let Traefik handle external ports, so we do not publish here.
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "14"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`neonova.sa`) || Host(`www.neonova.sa`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=3000"

  ########################################################################
  # TRAEFIK (Reverse Proxy + Let's Encrypt auto SSL)
  ########################################################################
  traefik:
    image: traefik:v2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    command:
      - "--api.insecure=true" # Enable dashboard
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true" # This enables TLS with the default cert
      - "--log.level=DEBUG"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=zaidalshreef@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "14"
